---
# tasks file for docker_compose
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install prerequisites for Docker repository setup
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - curl
    - gnupg
  become: yes

- name: Ensure directory exists for Docker GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present
  become: yes

- name: Get architecture
  command: dpkg --print-architecture
  register: architecture

- name: Get Ubuntu version codename
  shell: . /etc/os-release && echo "$UBUNTU_CODENAME"
  register: ubuntu_codename

- name: Add Docker repository
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch={{ architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] {{docker_repo_url }} focal stable

- name: Ensure Docker repository key file has correct permissions
  file:
    path: /etc/apt/keyrings/docker.gpg
    mode: '0644'
  become: yes

- name: Update apt package index
  apt:
    update_cache: yes
  become: yes

- name: Install Docker
  apt:
    name: docker-ce, docker-ce-cli, containerd.io, docker-buildx-plugin, docker-compose-plugin
    state: present
