version: "3.7"

services:
  nginx: # service name
    networks:
      - myweb_network
    container_name: nginx_c
    build: ./requirements/nginx
    volumes:
      - web-data:/var/www/html
      - ssl:/etc/nginx/ssl
    restart: unless-stopped # Always restart unless the developers forcibly stop the process
    expose: # publish the ports to the linked services of the container
      - "9000"
    ports:
      - "443:443/tcp" # host:container
    env_file: .env
    depends_on:
      - wordpress
  mariadb:
    networks:
      - myweb_network
    container_name: mariadb_c
    build: ./requirements/mariadb
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    env_file: .env
    expose:
      - "3306"
      - "8080"
  wordpress:
    networks:
      - myweb_network
    container_name: wordpress_c
    build: ./requirements/wordpress
    volumes:
      - web-data:/var/www/html
    restart: unless-stopped
    stdin_open: true # i
    tty: true # t
    env_file: .env
    expose:
      - "3306"
      - "9000"
      - "6379"
    depends_on:
      - mariadb
  phpmyadmin:
    networks:
      - myweb_network
    container_name: phpmyadmin_c
    build: ./requirements/phpmyadmin
    restart: unless-stopped
    stdin_open: true
    tty: true
    env_file: .env
    ports:
      - "8080:8080/tcp"
    depends_on:
      - mariadb

volumes:
  db-data:
    name: db-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/suahn/data/db
  web-data: # named volume can persist data after restart or remove a container
    name: web-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/suahn/data/web
  ssl:
    name: ssl
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/suahn/data/ssl

networks:
  myweb_network:
    driver: bridge